# Form implementation generated from reading ui file '.\boxscore_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BoxScoreWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timer_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.timer_label.setGeometry(QtCore.QRect(330, 20, 111, 71))
        self.timer_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.timer_label.setObjectName("timer_label")
        self.quarter_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.quarter_label.setGeometry(QtCore.QRect(360, 80, 51, 31))
        self.quarter_label.setObjectName("quarter_label")
        self.team_home_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.team_home_label.setGeometry(QtCore.QRect(70, 30, 191, 41))
        self.team_home_label.setObjectName("team_home_label")
        self.team_away_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.team_away_label.setGeometry(QtCore.QRect(540, 40, 191, 41))
        self.team_away_label.setObjectName("team_away_label")
        self.checkBox_home_1 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_home_1.setGeometry(QtCore.QRect(20, 180, 231, 41))
        self.checkBox_home_1.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_home_1.setObjectName("checkBox_home_1")
        self.checkBox_home_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_home_2.setGeometry(QtCore.QRect(20, 250, 231, 41))
        self.checkBox_home_2.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_home_2.setObjectName("checkBox_home_2")
        self.checkBox_home_3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_home_3.setGeometry(QtCore.QRect(20, 320, 231, 41))
        self.checkBox_home_3.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_home_3.setObjectName("checkBox_home_3")
        self.checkBox_home_4 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_home_4.setGeometry(QtCore.QRect(20, 380, 231, 41))
        self.checkBox_home_4.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_home_4.setObjectName("checkBox_home_4")
        self.checkBox_home_5 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_home_5.setGeometry(QtCore.QRect(20, 450, 231, 41))
        self.checkBox_home_5.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_home_5.setObjectName("checkBox_home_5")
        self.checkBox_away_1 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_away_1.setGeometry(QtCore.QRect(550, 190, 231, 41))
        self.checkBox_away_1.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_away_1.setObjectName("checkBox_away_1")
        self.checkBox_away_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_away_2.setGeometry(QtCore.QRect(550, 250, 231, 41))
        self.checkBox_away_2.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_away_2.setObjectName("checkBox_away_2")
        self.checkBox_away_3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_away_3.setGeometry(QtCore.QRect(550, 320, 231, 41))
        self.checkBox_away_3.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_away_3.setObjectName("checkBox_away_3")
        self.checkBox_away_4 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_away_4.setGeometry(QtCore.QRect(550, 390, 231, 41))
        self.checkBox_away_4.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_away_4.setObjectName("checkBox_away_4")
        self.checkBox_away_5 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_away_5.setGeometry(QtCore.QRect(550, 450, 231, 41))
        self.checkBox_away_5.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.checkBox_away_5.setObjectName("checkBox_away_5")
        self.checkbox_home_list = [
            self.checkBox_home_1, self.checkBox_home_2,
            self.checkBox_home_3, self.checkBox_home_4, self.checkBox_home_5
        ]
        self.checkbox_away_list = [
            self.checkBox_away_1, self.checkBox_away_2, self.checkBox_away_3,
            self.checkBox_away_4, self.checkBox_away_5,
        ]
        self.hide_elements(self.checkbox_away_list + self.checkbox_home_list)
        self.start_stop_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_stop_button.setGeometry(QtCore.QRect(370, 110, 41, 31))
        self.start_stop_button.setObjectName("start_stop_button")
        self.free_throw_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.free_throw_button.setGeometry(QtCore.QRect(310, 150, 75, 24))
        self.free_throw_button.setObjectName("free_throw_button")
        self.layup_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.layup_button.setGeometry(QtCore.QRect(400, 150, 75, 24))
        self.layup_button.setObjectName("layup_button")
        self.threepoint_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.threepoint_button.setGeometry(QtCore.QRect(310, 190, 75, 24))
        self.threepoint_button.setObjectName("threepoint_button")
        self.assist_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.assist_button.setGeometry(QtCore.QRect(400, 230, 75, 24))
        self.assist_button.setObjectName("assist_button")
        self.rebound_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rebound_button.setGeometry(QtCore.QRect(310, 230, 75, 24))
        self.rebound_button.setObjectName("rebound_button")
        self.missed_shot_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.missed_shot_button.setGeometry(QtCore.QRect(400, 190, 75, 24))
        self.missed_shot_button.setObjectName("missed_shot_button")
        self.steal_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.steal_button.setGeometry(QtCore.QRect(310, 280, 75, 24))
        self.steal_button.setObjectName("steal_button")
        self.turnover_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.turnover_button.setGeometry(QtCore.QRect(400, 280, 75, 24))
        self.turnover_button.setObjectName("turnover_button")
        self.home_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.home_score.setGeometry(QtCore.QRect(90, 90, 141, 61))
        self.home_score.setObjectName("home_score")
        self.away_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.away_score.setGeometry(QtCore.QRect(560, 90, 141, 61))
        self.away_score.setObjectName("away_score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timer_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">10:00</span></p></body></html>"))
        self.quarter_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Q1</span></p></body></html>"))
        self.team_home_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Team Home</span></p></body></html>"))
        self.team_away_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Team Away</span></p></body></html>"))
        self.checkBox_home_1.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_home_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_home_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_home_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_home_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_away_1.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_away_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_away_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_away_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_away_5.setText(_translate("MainWindow", "CheckBox"))
        self.start_stop_button.setText(_translate("MainWindow", "Start"))
        self.free_throw_button.setText(_translate("MainWindow", "+1"))
        self.layup_button.setText(_translate("MainWindow", "+2"))
        self.threepoint_button.setText(_translate("MainWindow", "+3"))
        self.assist_button.setText(_translate("MainWindow", "Assist"))
        self.rebound_button.setText(_translate("MainWindow", "Rebound"))
        self.missed_shot_button.setText(_translate("MainWindow", "Missed shot"))
        self.steal_button.setText(_translate("MainWindow", "Steal"))
        self.turnover_button.setText(_translate("MainWindow", "Turnover"))
        self.home_score.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">00</span></p></body></html>"))
        self.away_score.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">00</span></p></body></html>"))

    @staticmethod
    def hide_elements(list_of_elements: list):
        for item in list_of_elements:
            item.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_BoxScoreWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
