# Form implementation generated from reading ui file '.\game_start_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 383)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.team_home_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.team_home_label.setGeometry(QtCore.QRect(90, 100, 151, 81))
        self.team_home_label.setObjectName("team_home_label")
        self.team_away_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.team_away_label_2.setGeometry(QtCore.QRect(550, 100, 151, 81))
        self.team_away_label_2.setObjectName("team_away_label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 331, 91))
        self.label.setObjectName("label")
        self.combo_home = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_home.setGeometry(QtCore.QRect(90, 170, 131, 22))
        self.combo_home.setObjectName("combo_home")
        self.combo_away = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_away.setGeometry(QtCore.QRect(550, 170, 131, 22))
        self.combo_away.setObjectName("combo_away")
        self.start_game_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_game_button.setGeometry(QtCore.QRect(300, 220, 171, 31))
        self.start_game_button.setObjectName("start_game_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.team_home_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Team Home</span></p></body></html>"))
        self.team_away_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Team Away</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">Scory App</span></p></body></html>"))
        self.start_game_button.setText(_translate("MainWindow", "Start Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
